# Generated by Django 5.0.6 on 2024-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="customer_should_not_be_superuser",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("is_superuser", True), ("customer__isnull", False)),
                name="customer_should_not_be_superuser",
            ),
        ),
    ]
