# Generated by Django 5.0.6 on 2024-05-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_remove_user_customer_should_not_be_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="customer_should_not_be_superuser",
        ),
    ]
