# Generated by Django 5.0.6 on 2024-05-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_remove_user_customer_should_not_be_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="main_email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="auth_app.customer",
            ),
        ),
    ]
