# Generated by Django 5.0.6 on 2024-05-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0002_alter_task_assignee_alter_task_reporter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
