# Generated by Django 5.0.6 on 2024-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects_app",
            "0004_alter_project_description_alter_sprint_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "To Do"), (2, "In Progress"), (3, "Review"), (4, "Done")],
                default=1,
            ),
        ),
    ]
