# Generated by Django 5.0.6 on 2024-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects_app", "0005_task_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sprint",
            constraint=models.CheckConstraint(
                check=models.Q(("start_date__lte", models.F("end_date"))),
                name="start_date_must_be_before_end_date",
            ),
        ),
    ]
